name: Tests
on:
  pull_request:
    branches: ["master"]
jobs:
  Install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install
        run: npm install

      - name: Format
        run: npm run format:write

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:ci
